import * as fs from "node:fs";
import * as path from "node:path";

import { Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";

export interface DebugLogContext {
  operationType: string;
  entityId: string;
  userId: string;
  input?: any;
  output?: any;
  llmInput?: any;
  llmOutput?: any;
  metadata?: Record<string, any>;
}

@Injectable()
export class DebugLoggerService {
  private readonly logger = new Logger(DebugLoggerService.name);
  private readonly isEnabled: boolean;

  constructor(private readonly configService: ConfigService) {
    // Can be configured via environment variable or config
    this.isEnabled = this.configService.get<boolean>("ENABLE_DEBUG_LOGGING", false);
  }

  /**
   * Log API call with comprehensive debug information
   */
  async logApiCall(context: DebugLogContext): Promise<void> {
    if (!this.isEnabled) {
      this.logger.debug("Debug logging disabled, skipping API call log");
      return;
    }

    try {
      const logDir = path.join(process.cwd(), "logs");
      
      // Ensure logs directory exists
      if (!fs.existsSync(logDir)) {
        fs.mkdirSync(logDir, { recursive: true });
      }

      const fileName = `${context.operationType}-${context.entityId}-${Date.now()}.md`;
      const filePath = path.join(logDir, fileName);

      const markdown = this.generateMarkdownLog(context);
      
      fs.writeFileSync(filePath, markdown, "utf-8");
      
      this.logger.debug(`Debug log written: ${fileName}`);
    } catch (error) {
      this.logger.warn(`Failed to write debug log: ${error instanceof Error ? error.message : "Unknown error"}`);
    }
  }

  /**
   * Log resume generation specifically
   */
  async logResumeGeneration(
    jobApplicationId: string,
    userId: string,
    llmInput?: any,
    llmOutput?: any,
    apiOutput?: any,
  ): Promise<void> {
    await this.logApiCall({
      operationType: "resume-generation",
      entityId: jobApplicationId,
      userId,
      llmInput,
      llmOutput,
      input: llmInput,
      output: apiOutput,
    });
  }

  /**
   * Log cover letter generation
   */
  async logCoverLetterGeneration(
    jobApplicationId: string,
    userId: string,
    input?: any,
    output?: any,
  ): Promise<void> {
    await this.logApiCall({
      operationType: "cover-letter-generation", 
      entityId: jobApplicationId,
      userId,
      input,
      output,
    });
  }

  /**
   * Generic operation logging
   */
  async logOperation(
    operationType: string,
    entityId: string,
    userId: string,
    data?: any,
  ): Promise<void> {
    await this.logApiCall({
      operationType,
      entityId,
      userId,
      metadata: data,
    });
  }

  /**
   * Enable/disable debug logging at runtime
   */
  setEnabled(enabled: boolean): void {
    this.logger.log(`Debug logging ${enabled ? "enabled" : "disabled"}`);
  }

  /**
   * Check if debug logging is enabled
   */
  isDebugEnabled(): boolean {
    return this.isEnabled;
  }

  /**
   * Generate markdown content for debug log
   */
  private generateMarkdownLog(context: DebugLogContext): string {
    const sections = [
      "# API Call Debug Log",
      "",
      `**Operation**: ${context.operationType}`,
      `**Entity ID**: ${context.entityId}`,
      `**User ID**: ${context.userId}`,
      `**Timestamp**: ${new Date().toISOString()}`,
      "",
    ];

    if (context.input) {
      sections.push(
        "## Input Data",
        "```json",
        JSON.stringify(context.input, null, 2),
        "```",
        "",
      );
    }

    if (context.llmInput) {
      sections.push(
        "## LLM Input",
        "```json", 
        JSON.stringify(context.llmInput, null, 2),
        "```",
        "",
      );
    }

    if (context.llmOutput) {
      sections.push(
        "## LLM Output",
        "```json",
        JSON.stringify(context.llmOutput, null, 2), 
        "```",
        "",
      );
    }

    if (context.output) {
      sections.push(
        "## API Output",
        "```json",
        JSON.stringify(context.output, null, 2),
        "```",
        "",
      );
    }

    if (context.metadata) {
      sections.push(
        "## Additional Metadata",
        "```json",
        JSON.stringify(context.metadata, null, 2),
        "```",
        "",
      );
    }

    sections.push(
      "---",
      `*Generated by DebugLoggerService on ${new Date().toLocaleString()}*`,
    );

    return sections.join("\n");
  }
}

